### ISSUE TITLE
Reactive queries fail when using SSR

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher-react#36]
If you use a reactive query with SSR, the server crashes with the following error:

```sh
E20190102-15:40:30.205(1) (webapp_server.js:991) Error running template: TypeError: query.subscribe is not a function
    at props (packages/cultofcoders:grapher-react/lib/withReactiveQuery.js:17:42)
    at ReactMeteorDataComponent.getMeteorData (packages/react-meteor-data/ReactMeteorData.jsx:181:16)
    at MeteorDataManager.calculateData (packages/react-meteor-data/ReactMeteorData.jsx:34:24)
    at ReactMeteorDataComponent.componentWillMount (packages/react-meteor-data/ReactMeteorData.jsx:130:45)

[Lines left out]

    at sink (imports/startup/server/ssr-server.js:30:3)
    at onPageLoad.chain.callback (packages/server-render/server-register.js:14:19)
    at promise.then (packages/server-render/server.js:28:36)
    at /Users/Florian/.meteor/packages/promise/.0.11.1.1kty3c4.78s++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

I'm not sure what the best way of solving this is, since we can't subscribe to data on the server?

**Comment by liitfr** [comment]
Hello,
I believe @abecks started to work on this : 
https://github.com/cult-of-coders/grapher-react/pull/22
